apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyuui9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fyuui9
  template:
    metadata:
      labels:
        app: fyuui9
    spec:
      containers:
      - image: okteto.dev/fyuui9:latest
        name: fyuui9
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "bcea0a66-f8bd-4a83-bab7-6b6600ac816f"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "bcea0a66-f8bd-4a83-bab7-6b6600ac816f"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
