apiVersion: v1
kind: Service
metadata:
  name: fyuui9
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "fyuui9"
    port: 8080
  selector:
    app: fyuui9
